### ISSUE TITLE
Single quotes instead of double

### ISSUE THREAD

**Issue by rudiedirkx** [jbjonesjr/letsencrypt-manual-hook#11]
This isn't copyable very easily:

    Create TXT record for the domain: "_acme-challenge.games.example.com". TXT record:
    "hiznC7AoUeZIjLF0__3fikKGZUyr5AkWyK91uzfGwXc"

because double quotes are selected when you double click the value.

But this is:

    Create TXT record for the domain: '_acme-challenge.games.example.com'. TXT record:
    'hiznC7AoUeZIjLF0__3fikKGZUyr5AkWyK91uzfGwXc'

and since copy & paste is a big part of the process, making it easier would be nice.

**Comment by jbjonesjr** [comment]
What OS/tool?

For me (Mac OSX) a double click is just the inside of the quotes.

> and since copy & paste is a big part of the process, making it easier would be nice.

Yes, totally want to make this easy.

**Comment by rudiedirkx** [comment]
Ah, yes, of course. That's different for every single terminal... I'm using Putty on Windows. I'm guessing Putty is the boss of selection logic. Double click selection is different everywhere. In browsers `-` would be a delimiter, but in Putty it selects right over it. Same for `"`.

I'm not sure there can be a one-size-fits-all...

**Comment by rudiedirkx** [comment]
Maybe wrap copyable values in `[` and `]`. I think they're uncopyable everywhere, but it's not very obvious what they mean... Do with it what you will.

**Comment by jbjonesjr** [comment]
Hey @rudiedirkx , didn't mean to ignore this, it slipped through the cracks.

At least for me(:tm:), single quotes and double quotes are the same, so I don't see any reason why they can't be replaced.

> I'm not sure there can be a one-size-fits-all...

That's true. But if single-quote is more accessible, then :+1:.

`[`, `]`are a very interesting idea. But it's ... gross. I'm going to PR to single quotes, and i'm open for additional improvements if others want improvements.
